### ISSUE TITLE
On Logout: "Application error: a client-side exception has occurred (see the browser console for more information)."

### ISSUE THREAD

**Issue by creativcoder** [SarathAdhi/next-supabase-auth#3]
Hi, thank you for creating this template.

I have been trying to set this up and the supabase login and signup works out as expected (no additional changes expect just replacing my env vars). It's only when I click on logout I get this error:

```
Application error: a client-side exception has occurred (see the browser console for more information).
```

Any ideas to solve this? I tried to understand the debug logs but it doesn't point towards anything in the source file. From quick search on the error string, leads me to the issue that somewhere we're not passing data in a proper json format. But i don't know where that issue is originating from

**Comment by SarathAdhi** [comment]
The issue might be because of the server actions. 
In the navbar component, we have to make the logout function as client component and write the function inside that component itself instead of using server action

**Comment by SarathAdhi** [comment]
This issue is now fixed, hence i am closing this..

#4
